---
title: "Thoughts on Advent of Code 2020"
description: |
  Quick reflection on AoC 2020 puzzles
draft: true
categories:
  - advent of code
  - puzzles
author:
  - name: Sam Parmar
    url: https://parmsam.github.io/
date: 12-24-2020
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# What is Advent of Code?
Advent of Code is an annual programming challenge created by [Eric Wastl](http://was.tl/). It starts on December 1 of each year, releasing a unique puzzle daily until December 25. You can use any programming language to solve the problems. There are usually 25 unique puzzles in each annual set, with two parts per puzzle.

Learn more about the challenge at <https://adventofcode.com/2020/about>. This blog post will collect my thoughts as I complete the 2020 puzzles in R. This [repo](https://github.com/parmsam/aoc-2020) has all my inputs and code.

# Who should do the challenge?
Folks with prior knowledge and basic skills in any programming language. It is great opportunity to test and refine your skills. The contest is, in my opinion, great for folks with Pandas + Numpy experience in Python or Tidyverse experience in R.

# How did I do?
| Day  | Part One | Part Two | 
|---|:---:|:---:|
| Day 1: Report Repair| ⭐️ | ⭐️ |
| Day 2: Password Philosophy| ⭐️ | ⭐️ |
| Day 3: Toboggan Trajectory| ⭐️ |  |
| [Day 4: Passport Processing](https://parmsam.github.io/aoc-2020/aoc-2020-solutions-day4.html)| ⭐️ | ⭐️ |
| [Day 5: Binary Boarding](https://parmsam.github.io/aoc-2020/aoc-2020-solutions-day5.html)| ⭐️ | ⭐️ |
| [Day 6: Custom Customs](https://parmsam.github.io/aoc-2020/aoc-2020-solutions-day6.html)| ⭐️ | ⭐️ |
| Day 7: Handy Haversacks| ⭐️ | ️ |

# What was my approach?
- Day 1:
- Day 2: 
- Day 3:
- Day 4: Used combination of strsplit() and unnest() to get character vector then split it into rows. Understanding of spread() and gather() helped with this exercise. Just used filter() to apply Part B passport conditions. Understanding of regex makes this straightforward. Boundary escape characters were needed in some filters. 
- Day 5: Used regex to get flight row (FB) and flight column position strings (BR) into seperate variables. Custom function needed reminded me of binary search. Used purrr map() function to apply custom function on relevant flight row  or flight column. Then arrange(), rbind(), cbind(), and filter() helped identify missing seat, by just sorting seat ID numbers adding expected seat ID numbers column and filtering for difference.
- Day 6: The purrr map() function made this exercise straightforward. Got to use more map2 to pass multiple parameters through a custom function to get questions where everyone answered yes in each group.

# Any other thoughts?
