---
title: "My Favorite Blog Posts of 2020"
description: |
  On data science with self help
draft: false
author:
  - name: Sam Parmar
    url: https://parmsam.github.io/
date: 01-01-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[Paul Graham’s Blog — Life is Short](http://www.paulgraham.com/vb.html)

* The first essay I read from Paul Graham (co-founder of Y Combinator). Encourage anyone reading to check this post out. It’s a short essay but it’s packed full of experience-based insight.
One of my favorite parts — “Relentlessly prune bullshit, don’t wait to do things that matter, and savor the time you have. That’s what you do when life is short.” -Paul Graham

[Suzan Baert’s Blog — Data Wrangling Series (Parts 1-4)](https://suzan.rbind.io/2018/01/dplyr-tutorial-1/)

* First stumbled upon this four blog post series in late 2019. I wish I had earlier. It provides a great overview of data wrangling with dplyr - from basic into advanced. I’ve revisited it on a several occasions in 2020. Suzan did a great job explaining functions like select_if(), mutate_if(), mutate_at(), and filter_if(). Some of the best explanations I’ve read of advanced tidyverse functions. The posts build upon each other.

[RStudio Blog — (Re-)introducing Distill for R Markdown by Alison Hill and JJ Allaire](https://blog.rstudio.com/2020/12/07/distill/)

* This article introduced me to one of my favorite packages of 2020 and led me to start my own Distill blog. Specifically, I love the site-wide search functionality, favicon support, and overall aesthetic. Post provides and overview of the package features.

[Shamindras Shotriya’s Blog — Upgrading Distill Blog Settings](https://www.shamindras.com/posts/2019-07-31-shrotriya2019distillpt2/)

* Awesome article that showed me how to take my Distill Blog to the next level. It shows you how to setup Disqus comments, Google Analytics, Blog Post Sharing options, and Change/Corrections tracking. Shamindras did a great job documenting his process.

[Rebecca Barter’s Blog — Learn to purrr](http://www.rebeccabarter.com/blog/2019-08-19_purrr/)

* This blog post taught me more about the Purrr package in R. Great resource to learn more about the package’s main functions. I’ve started using more map() functions as a direct result of this article.

### Extra

[RStudio Blog — Winners of the 2nd Annual Shiny Contest](https://blog.rstudio.com/2020/07/13/winners-of-the-2nd-shiny-contest/)

* Had to throw this in there. My submission made it to the runner up list. It was my first R Shiny project for public use. Great learning experience since I had only been using R Shiny for less than one year. I encourage anyone reading to check out the other winners. The other submissions were absolutely amazing.




